#!/bin/bash

set -euC
# set -o pipefail

# exec 5>> /tmp/xmosh/shell-script-debug.out
# BASH_XTRACEFD="5"
# PS4='$LINENO: '
# set -x

dir="$(dirname "$(readlink -f "$0")")"

exec uv run \
  --directory "$dir" \
  rename-movies \
  -- \
  rename \
  "$@"
